[functions]
  directory = "api"
  included_files = ["wp/**"]
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
[template.environment]
  DATABASE = "serverlesswpx"
  USERNAME = "ybh19tbedj591xv36sfk"
  PASSWORD = "pscale_pw_5oX8f7OWn2mCLDNnLGcZTC8SQr58ugQMaXJobhaeYl3"
  HOST = "aws.connect.psdb.cloud"