service: serverlesswp-wordpress-starter

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    payload: '2.0'

functions:
  requestHandler:
    handler: api/index.handler
    memorySize: 1024
    timeout: 15
    events:
      - httpApi:
          method: any
          path: /{proxy+}
    environment:
      #DATABASE: ''
      #USERNAME: ''
      #PASSWORD:Dosyayı teslim edecekseniz bunu ayarlamayın; bunun yerine AWS konsolunu veya Parametre Deposu gibi başka bir yöntemi kullanın.
      #HOST: ''